@startuml
skinparam wrapwidth 200

package "req [Package] Non functional requirements [requirement diagram]" {
    stereotype "Pagination" as pagination <<Requirement>> {
        overview = When displaying a list, either patrons or books, implement an infinite pagination display.
    }

    stereotype "Magic data" as magic_data <<Requirement>> {
        overview = UI should not show sensible data
    }

    stereotype "User Interface" as  user_interface <<Requirement>> {
        overview = Create a user-friendly console interface that guides users through the available functionalities. The interface should be intuitive and provide clear instructions and feedback 
    }
    user_interface <.. magic_data: <<deriveReqt>>
    user_interface <.. pagination: <<deriveReqt>>

    stereotype "Logging" as logs <<Requirement>> {
        overview = Log events
    }

    stereotype "Error Handling and Validation" as  error_handling_validation <<Requirement>> {
        overview = Implement robust error handling and input validation to ensure the system is stable and reliable.
    }
    error_handling_validation <.. logs: <<deriveReqt>>

    stereotype "Performance" as  performance <<Requirement>> {
        overview = The system should have a low footprint
    }

}
@enduml
