@startuml
package "Book management" {

    class Book {
        - id: int
        - title: string
        - author: string
        - isbn: string
        - genre: string
        - publicationYear: string
    }

    class BookRepository {
        - booksCollection: Book[]

        + add(book Book): void
        + delete(Id int): void
        + update(Id int, book Book): void
        + get(Id int): Book
        + getAll(): Book[]
    }
    BookRepository o-- Book

}
@enduml
    class {
    }

